version: '3.8'

networks:
  docker-network:
    driver: bridge

services:
  db:
    image: postgres:16-alpine3.18
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    networks:
      - docker-network
